ASPNETCore_ChatApp/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNETCore_ChatApp.ViewModels
{
    public class LoginViewModel
    {
        [Required, MaxLength(256)]
        [DisplayName("User Name")]
        public string UserName { get; set; }

        [Required, MaxLength(256)]
        public string Password { get; set; }

        public bool RememberMe { get; set; }
    }
}

ASPNETCore_ChatApp/ViewModels/RegisterViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNETCore_ChatApp.ViewModels
{
    public class RegisterViewModel
    {
        [Required, MaxLength(256)]
        [DisplayName("Username")]
        public string UserName { get; set; }

        [Required, MaxLength(256)]
        [EmailAddress]
        public string Email { get; set; }

        [Required, DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password), Compare(nameof(Password))]
        [DisplayName("Confirm Password")]
        public string ConfirmPassword { get; set; }

        public IFormFile Image { get; set; }
    }
}

ASPNETCore_ChatApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ASPNETCore_ChatApp.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("Panel");
        }

        public IActionResult Login()
        {
            return View();
        }
        [Route("Admin/ListUsers")]
        public IActionResult ListUsers()
        {
            return View();
        }

        [Route("Admin/ListUsers/{username:string}")]
        public IActionResult ListUsers(string username)
        {
            return View();
        }
    }
}

ASPNETCore_ChatApp/Controllers/ChatController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASPNETCore_ChatApp.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using MySql.Data.MySqlClient;
using Microsoft.AspNetCore.Identity;
using ASPNETCore_ChatApp.Helper;
using ASPNETCore_ChatApp.ViewModels;

namespace ASPNETCore_ChatApp.Controllers
{
    public class ChatController : Controller
    {
        public IdentityUserHandler UserHandler;
        public ChatController(UserManager<IdentityUser> userManager, 
            SignInManager<IdentityUser> signInManager)
        {
            UserHandler = new IdentityUserHandler(userManager, signInManager);
        }

        public ChatDBContext MySqlDBContext
        {
            get
            {
                return HttpContext.RequestServices.GetService(typeof(ChatDBContext)) as ChatDBContext;
            }
        }

        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel login)
        {
            if (ModelState.IsValid)
            {
                var user = await UserHandler.UserManager.FindByNameAsync(login.UserName);

                if (user == null)
                {
                    Debug.WriteLine("User is null: ");
                    ModelState.AddModelError(string.Empty, "Invalid login");
                    return View();
                }
                var passwordSignInResult = await UserHandler.SignInManager.PasswordSignInAsync(user, login.Password, isPersistent: login.RememberMe, lockoutOnFailure: false);
                if (!passwordSignInResult.Succeeded)
                {
                    Debug.WriteLine("Invalid login password");
                    ModelState.AddModelError(string.Empty, "Invalid login password");
                    return View();
                }
                try
                {
                    User userData = MySqlDBContext.GetUser(login.UserName, login.Password);
                    MySqlDBContext.UpdateUserStatus(user.UserName, "Online");
                    return RedirectToAction("Hub", new { user = userData.Username });
                }
                catch (MySqlException ex)
                {
                    Debug.WriteLine("Mysql Error: " + ex.Message);
                }
            }
            else
            {
                Debug.WriteLine("ModelState Error: " + string.Join(" | ", ModelState.Values
                .SelectMany(v => v.Errors)
                .Select(e => e.ErrorMessage)));
            }      

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            var currentUser = Request.HttpContext.User.Identity.Name;

            await UserHandler.SignInManager.SignOutAsync();
            MySqlDBContext.UpdateUserStatus(currentUser, "Offline");
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel register)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    User user = new User()
                    {
                        Username = register.UserName,
                        Email = register.Email,
                        Password = register.Password,
                        Image = null
                    };

                    if (register.Image != null && register.Image.Length > 0)
                    {
                        var fileName = Path.GetFileName(register.Image.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", fileName);
                        using (var fileSteam = new FileStream(filePath, FileMode.Create))
                        {
                            await register.Image.CopyToAsync(fileSteam);
                        }
                        user.Image = fileName;
                    }
                    MySqlDBContext.InsertUser(user);
                    await UserHandler.CreateUser(user.Username, user.Email, user.Password);
                    return RedirectToAction("Login");
                }
                catch (MySqlException ex)
                {
                    Debug.WriteLine("Mysql Error: " + ex.Message);
                }
            }
            else
            {
                Debug.WriteLine("ModelState Error: " + string.Join(" | ", ModelState.Values
                .SelectMany(v => v.Errors)
                .Select(e => e.ErrorMessage)));
            }
            
            return View();
        }

        public IActionResult Hub(string user)
        {
            var currentUser = Request.HttpContext.User.Identity.Name;

            Debug.WriteLine("loggedInUser: " + currentUser);
            if (!string.IsNullOrEmpty(user) && currentUser == user)
            {
                try
                {
                    User userData = MySqlDBContext.GetUserByUname(user);
                    return View(userData);
                }
                catch (NullReferenceException ex)
                {
                    Debug.WriteLine("Error: " + ex.Message);
                    return RedirectToAction("Login");
                } 
            }
            return RedirectToAction("Login");
        }

        protected void Session_End()
        {

        }

        [HttpPost]
        public bool IsUserAvailable(string username)
        {
            var IsUserExist = MySqlDBContext.IsUsernameExist(username);
            Debug.WriteLine("IsUsernameExist: " + IsUserExist);
            return IsUserExist;
        }

        [HttpPost]
        public bool IsEmailAvailable(string email)
        {
            var IsUserExist = MySqlDBContext.IsEmailExist(email);
            Debug.WriteLine("IsEmailAvailable: " + IsUserExist);
            return IsUserExist;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPNETCore_ChatApp/Views/Chat/Hub.cshtml
@model ASPNETCore_ChatApp.Models.User

@{
    ViewData["Title"] = "ChatHub";

}

<div class="container">
    <div class="d-flex justify-content-between col-12 pt-3 pb-2">
        <h1>ChatHub</h1>
        <a href="@Url.Action("Logout","Chat")" class="btn btn-dark my-auto text-white">Logout</a>
    </div>
    <div class="row">
        <!--USER PANEL-->
        <div class="col-xs-12 col-sm-4 col-md-3 list-panel">
            <div class="text-white">
                <div class="d-flex flex-row my-4">
                    <div class="d-flex">
                        <img id="userImg" data-senderid="@Model.Id" class="my-auto img-round" src="~/img/@Model.Image" alt="user" width="34" height="34" />
                    </div>
                    <div class="d-flex flex-wrap align-content-center h-100">
                        <h5 id="username" class="text-white mb-0 col-12">@Model.Username</h5>
                        <p class="statusTxt text-secondary mb-0 col-12">@Model.Status</p>
                    </div>
                </div>
                <div>
                    <div class="d-flex justify-content-between">
                        <p class="text-white mb-0 text-nowrap" >Chats</p>
                        <span>(<span id="usersCount"></span>)</span>
                    </div>
                    <hr class="bg-white mt-0" />
                </div>
            </div>
            <ul class="nav"></ul>
            <a href="@Url.Action("Login","Admin")" class="admin-link">Admin</a>
        </div>
        <!--MESSAGE PANEL-->
        <div class="col-xs-12 col-sm-8 col-md-9 message-panel">
            
            
            <div class="chat-sect h-100">
                <div class="d-flex pb-1">
                    <img id="backBtn" class="my-auto mr-2 border" src="~/img/baseline_arrow_back_white_18dp.png" />
                    <h3 class="text-white py-3 m-0">Your conversation with <span id="convo_partner_name" class="text-dark">convo_partner_name</span></h3>
                </div>   
                <span id="isTyping" class="text-center pb-1"></span>
                <div class="message-box">
                    <div class="message-status">message sent</div>
                </div>
                <input type="hidden" id="userInput" value="@Model.Username" />
                <div class="message-input d-flex">
                    <input type="text" id="messageInput" class="form-control" placeholder="Write a message" />
                    <button id="sendButton" class="btn">Send</button>
                </div>
            </div>
            <div class="no-chat h-100">
                <h3 class="text-center align-self-center flex-grow-1">Select an online user to begin chat</h3>
            </div>
        </div>
    </div>
</div>

<script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <!--<script src="~/lib/jquery/dist/jquery.signalr-2.2.js"></script>-->
    <script src="~/js/chat.js"></script>

ASPNETCore_ChatApp/Views/Chat/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASPNETCore_ChatApp/Views/Chat/Login.cshtml
@{
    ViewData["Title"] = "ASPNETChat - Login";

    <script type="text/javascript">
        window.onload = function () {
            document.getElementById("submitBtn").addEventListener("click", function (event) {
                window.sessionStorage.setItem("uname", document.getElementById("username").value);
            });
        };
    </script>
}



    <div class="container w-50" style="margin-top: 100px">
        <div class="d-flex">
            <img class="mx-auto" src="~/img/user (1).png" width="150" height="150" />
        </div>
        <p class="text-center">Enter your information to login to your account</p>
        <form id="loginForm" class="mt-5" asp-controller="Chat" asp-action="Login" method="post">
            <div class="form-group">
                <label>Username</label>
                <input type="text" class="form-control" name="UserName" id="username" />
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="password" class="form-control" name="Password" />
            </div>
            <div class="d-flex justify-content-between">
                <label><input name="rememberMe" checked="checked" type="checkbox" value="true" /> &nbsp;Remember me</label>
                <a href="@Url.Action("Register", "Chat")">Need an account?</a>
            </div>
            <div class="py-2 d-flex justify-content-end">
                <button type="submit" id="submitBtn" class="btn">Login</button>
            </div>
        </form>
        @if (!ViewContext.ModelState.IsValid)
        {
            <div class="alert alert-danger">
                <div asp-validation-summary="All"></div>
            </div>
        }
    </div>

ASPNETCore_ChatApp/Views/Chat/Register.cshtml
@{
    ViewData["Title"] = "Register";

    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            document.getElementById("username").addEventListener("focusout", (event) => {
                let username = event.currentTarget.value;
                $.ajax({
                    type: 'POST',
                    url: "IsUserAvailable",
                    data: { username: username }
                }).done(function (result) {
                    if(result)
                        $(".username-error").html("Username is unavailable");
                    else
                        $(".username-error").empty();
                });

            });

            document.getElementById("email").addEventListener("focusout", (event) => {
                let email = event.currentTarget.value;
                $.ajax({
                    type: 'POST',
                    url: "IsEmailAvailable",
                    data: { email: email }
                }).done(function (result) {
                    if (result)
                        $(".email-error").html("Email is unavailable");
                    else
                        $(".email-error").empty();
                });
            });
        };
    </script>
}

<div class="container w-50" style="margin-top: 100px">
    <div class="d-flex">
        <img class="mx-auto" src="~/img/user (1).png" width="150" height="150" />
    </div>
    <p class="text-center">Create a new account</p>
    <form class="mt-5" asp-controller="Chat" asp-action="Register" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" name="UserName" id="username" />
            <div class="text-danger username-error"></div>
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" name="Email" id="email" aria-describedby="emailHelp" />
            <div class="text-danger email-error"></div>
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" name="Password" />
        </div>
        <div class="form-group">
            <label>Confirm Password</label>
            <input type="password" class="form-control" name="ConfirmPassword" />
        </div>
        <div class="form-group">
            <label>Upload image</label>
            <input type="file" class="form-control-file" name="Image" />
        </div>
        <div class="py-3 d-flex justify-content-between">
            <a href="@Url.Action("Login", "Chat")">Back to login</a>
            <button type="submit" class="btn">Register</button>
        </div>
    </form>
    @if (!ViewContext.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            <div asp-validation-summary="All"></div>
        </div>
    }
</div>